### ISSUE TITLE
Replaylast or similar needed

### ISSUE THREAD

**Issue by DarthMike** [ReactKit/ReactKit#27]
It would be good to have  a signal which executes only one time, and then it returns same result. 

I understand it's not 'pure', but it is really useful to build applications, specially when you deal with network requests and avoiding duplicate work.

Do you have any suggestions on how to best achieve this with current API?

**Comment by inamiy** [comment]
Thanks for feedback again :smiley: 
I'm currently working on this, so I'll mark this issue as *enhancement* request.

- [ ] Add `replay()` & `replayLast()`

Unfortunately, implementing `replay()` in current ReactKit v0.8.1 is not recommended because it mostly focuses on hot-and-lazy signal only, whereas calling `replay()` requires cold signal.

But don't worry! In future v0.10.0 as discussed in https://github.com/ReactKit/ReactKit/pull/26, the concept of Stream Producer (`Void -> Stream<T>`) will appear and will work just like cold signal, so I will implement in the next version.

**Comment by inamiy** [comment]
I added `prestart()` feature in #26 https://github.com/ReactKit/ReactKit/commit/31415065887ad630c8af08fcb25865c9a863aa26 
which should work just like Rx's `replay()`, so please check it.

```
/// Creates an upstream from `upstreamProducer`, resumes it (prestart),
/// and caches its emitted values (`capacity` as max buffer count) for future "replay"
/// when returning streamProducer creates a new stream & resumes it,
/// a.k.a. Rx.replay().
public func prestart<T>(capacity: Int = Int.max) -> (upstreamProducer: Stream<T>.Producer) -> Stream<T>.Producer
```

For `replayLast()`, it's technically same as `prestart(capacity: 1)`.

This operation works for `Stream<T>.Producer` (`Void -> Stream<T>`) type (a.k.a "cold" stream),
so **normal stream needs to lift up to streamProducer and operate with new `|>>` pipelining operator**.
There is a test case example available in [StreamProducerTests.swift#L93-L154](https://github.com/ReactKit/ReactKit/blob/31415065887ad630c8af08fcb25865c9a863aa26/ReactKitTests/StreamProducerTests.swift#L93-L154).

By the way, **I decided to add a new name** for this operation because this doesn't actually replay the true "timing" of the emission of values, but only its buffered "sequence".
So, it's mainly focused on caching the values, and other words like `precache` or `resumeAndBuffer` might fit better.
Currently, I'm on to the most intuitive `prestart`.

Do you have any thoughts on naming?

**Comment by DarthMike** [comment]
Nice! :clap: 

I'm a bit confused with naming though. I'm up for consistency with the `replay` terminology. I'm not sure if `Rx.replay()` also replays the timing, but I suggest keeping that name anyway.

**Comment by inamiy** [comment]
Thanks for feedback :)
To conform to Rx semantics for Rx users, I also added `replay()` as an alias name in 21d9ac4,
so this should fulfill your needs :+1:

#### P.S.

I found RxJS replaying the timing well as illustrated in
[replay | RxJS - Javascript library for functional reactive programming.](http://xgrommx.github.io/rx-book/content/core_objects/observable/observable_instance_methods/replay.html)
when you pass extra first argument as non-null.
To me, this can be truly called as "replay", but in ReactKit, it can be done just by creating Stream<T>.Producer and producing lazy-starting-streams separately 
(so you don't even need `replay()` for replaying!).
