### ISSUE TITLE
Signals auto deinit upon creation?

### ISSUE THREAD

**Issue by LightD** [ReactKit/ReactKit#30]
Hi,
I can't seem to be able to create a signal using the init closure.. whenever I create a signal it automatically goes into failure block.. here's a test signal:

```swift
let signal = Signal<String> { (progress, fulfill, reject, configure) -> Void in
        
            progress("pffft, lets see")
            println("created signal successfully")
            
            }.progress({ (oldProgress, newProgress) -> Void in
                println(newProgress)
            })
            .success { value -> Void in
                println("singal is finished")
            }.failure({ (error, isCancelled) -> Void in
                println(error!.localizedDescription)
                println("is cancelled: \(isCancelled)")
            })
```

`error!.localizedDescription` is printing: `Signal=DefaultSignal is cancelled via deinit.`
Am I doing something wrong? or is there something wrong in the framework (which I doubt actually)?

**Comment by inamiy** [comment]
Hi, thanks for feedback :smile: 

In your case, `initClosure` will not be invoked because **`Signal` is lazily evaluated**
(actually, I should call `lazyInitClosure`) and it is deallocated before its first run.
In order to start its running, you need to call `signal.resume()`, or use `<~` or `~>` binding operator,
which is equivalent to `signal.react()` that performs `progress()` and `resume()` together.

So your code should look like this:
	
```swift
let signal = Signal<String> { (progress, fulfill, reject, configure) -> Void in
            
    progress("pffft, lets see")
    println("created signal successfully")
    
}.react { newProgress -> Void in
    println(newProgress)
}
// use `react()` instead of `progress()`

// NOTE: using `success()` / `failure()` will return `Task`, not `Signal`, so I separated the method-chaining intentionally
let task = signal.success { value -> Void in
    println("singal is finished")
}.failure({ (error, isCancelled) -> Void in
    println(error!.localizedDescription)
    println("is cancelled: \(isCancelled)")
})
```

This will print:

```
[init] <DefaultSignal; state=Paused>
pffft, lets see
created signal successfully
[deinit] <DefaultSignal; state=Running>
Signal=DefaultSignal is cancelled via deinit.
is cancelled: true
```

Also, if you want to just use `progress()`/`success()`/`failure()` control flow, 
you can use [ReactKit/SwiftTask](https://github.com/ReactKit/SwiftTask) instead.
(These method are for `Task` rather than `Signal`)

**Comment by LightD** [comment]
Thank you so much for your help, I didn't find a clue to your answer in the documentation or unit tests, that's why i asked here.. I'll try and see what i can come up with :)
Thanks a lot for the help :)
