### ISSUE TITLE
question - How to react?

### ISSUE THREAD

**Issue by d6u** [ReactKit/ReactKit#51]
I want a simple stream:

``` swift
Stream.sequence([1,2,3,4])
            |> map { (n: Int) -> Void in
                return n * 2
            }
            |> react { // use of unresolved identifier 'react'
                println($0)
            }
```

But it said "use of unresolved identifier 'react'". I was confused how to apply `react`?

Also is it possible to construct a stream and dispatch change manually? E.g.

``` swift
let stream = Stream<String>()
stream.map { ... }
    .react { ... }

// later on
stream.dispatch("change")
```

**Comment by inamiy** [comment]
In current ver 0.11.4 (for Swift 1.2), `|>` is used for constructing stream-pipelining and not for activating (`react`) it, so you should use `~>` (or `~>!` for less operator precedence) instead.

``` swift
Stream.sequence([1,2,3,4])
            |> map { (n: Int) -> Void in
                return n * 2
            }
            ~>! react {
                println($0)
            }

// or, use plain dot-syntax `.react()`
let stream = Stream.sequence([1,2,3,4]) |> map { ... }
stream.react { ... }
```

BTW, I'm planning to remove these custom operators in future, since constrained extensions will be supported in Swift 2.

For manual dispatching stream (like Rx.Subject), unfortunately there's no class available now.
But easy alternative would be to create some `dynamic var` property and create its KVO stream.

**Comment by d6u** [comment]
I see. Thanks!
